### PR TITLE
Update transcript with fix for unintelligible text

### PR DESCRIPTION
**Pull request by DavidJFelix**
- https://github.com/octobox/octobox
- https://github.com/andrew

### CODE REVIEW

**Comment by jerodsanto** [comment]
👍 @DavidJFelix if you want to add those as links in the text we're totally down with that, too.

**Comment by DavidJFelix** [comment]
I had planned on doing that but I wasn't actually sure how links were going to be parsed. I looked in this transcript for examples but didn't find anything, so I just didn't add them to prevent any headaches.

Is it just Github-flavored-markdown style?

```
[Andrew Nesbitt](https://github.com/andrew)
```
Like this?

**Comment by jerodsanto** [comment]
You got it. Markdown-stylee 👍

**Comment by DavidJFelix** [comment]
Done 👍

**Comment by jerodsanto** [comment]
Your improvements are now live on-site!

https://changelog.com/podcast/264#transcript

Thanks so much for being a part of our community 💚💚💚

**Pull request merged**
