### PR TITLE
Fixed unintelligibles in FoundersTalk Ep72

### PR DESCRIPTION
**Pull request by ritikeshvali**

### CODE REVIEW

**Review by pnevares — CHANGES_REQUESTED** [review]
If you can make the change Jerod suggested, this should be fine to merge! ❤️

**Comment by ritikeshvali** [comment]
I'm sorry, accidentally resolved it. I'll correct it.

**Comment by ritikeshvali** [comment]
Made the changes.

**Review by pnevares — APPROVED** [review]
Thank you! 🚀

**Pull request merged**
