### PR TITLE
fix: typos

### PR DESCRIPTION
**Pull request by nasirhm**
Fixed some typos like : dox, an.

Added standard library too.

### CODE REVIEW

**Comment by pnevares** [comment]
@nasirhm If possible, please combine changes for the same episode into one pull request. Your hard work is appreciated! 💙

**Comment by nasirhm** [comment]
Sure, Would send combined PRs, Thank You for the merges @pnevares :)

**Comment by hhrutter** [comment]
Hello!

@nasirhm 
@pnevares 

The git history for this repo is getting messy.
Can we please stick to mentioning the episode a fix is supposed to be for.

eg. if a commit fixes a typo or unintelligible in the go time episode 4 then the commit message should look like:
`Fix typos in go-time-4.md`

Thank you!

**Comment by nasirhm** [comment]
Hey @hhrutter , Thanks, would use the commit message as you defined for git history.

Thank You

**Comment by hhrutter** [comment]
👍 
I just try the follow the best practises like explained here:
https://chris.beams.io/posts/git-commit/

**Pull request merged**
