### PR TITLE
Added a word at the unintelligible part

### PR DESCRIPTION
**Pull request by jonascarlsonschmidt**

### CODE REVIEW

**Comment by jerodsanto** [comment]
Are there more unintelligible words left at that point? If not, you can also remove the "unintelligible" section and the timestamp.

**Comment by jonascarlsonschmidt** [comment]
There is one word left. Maybe it is "word". But does "that's a bad word joke" make sense?

**Comment by jerodsanto** [comment]
Listened back and I don't even know what he said.

> bad word joke?

> backwards joke?

Paging @adamstac... 📲

**Comment by pnevares** [comment]
My ears hear something closer to "Scalable AI. That's a bad first show". 🤔

**Comment by sgvictorino** [comment]
I think I heard "backwards joke" at [00:15:38](https://changelog.com/backstage/1#t=00:15:38), but I could be completely wrong.

**Comment by jerodsanto** [comment]
se la vi. Let's just merge this and move on with our lives.

**Pull request merged**
