### PR TITLE
Added timestamps to all episodes of afk

### PR DESCRIPTION
**Pull request by kishorerabha**
Added convenient timestamps to each transcript for when the conversation actually begins between the host Tim and his guests at the beginning of each podcast.

### CODE REVIEW

**Comment by jerodsanto** [comment]
Super cool! Does each of these conversations actually start at 1:46? Either he's doing that on purpose or something is up... 🤔

**Comment by kishorerabha** [comment]
Thanks. The actual conversation always begins after an ad followed by an intro :) Should I try adding similar timestamps to the other podcasts as well?

**Comment by jerodsanto** [comment]
That makes sense. I couldn't recall if he had any non-canned intro stuff in there. Yes, we will take all the timestamps you're willing to add! 💚💚💚

**Comment by kishorerabha** [comment]
thank you :)

**Pull request merged**
