### PR TITLE
Transcribed an unintelligible in The Changelog #298

### PR DESCRIPTION
**Pull request by bitsol**

### CODE REVIEW

**Comment by jerodsanto** [comment]
Your fix is live on the site, thanks! 💚💚💚

**Comment by jerodsanto** [comment]
@bitsol that's 3 awesome contribs in a row! Is this gonna become a regular thing for ya? If so, I'm happy to give you the commit bit so you don't have to go through the PR flow. ✊

**Comment by bitsol** [comment]
@jerodsanto These podcasts are so great I can't stop listening to them 😄 , and I'll likely find ways to help because of that, so I think it would be cool if I could be a collaborator on this repo.
Thanks!

**Comment by jerodsanto** [comment]
@bitsol invite sent! 💚 

Glad you're enjoying our shows. Feel free to come hang out with us in Slack if you like, too. 💯 

https://changelog.com/community

**Pull request merged**
