### PR TITLE
correction to transcript - missing spoken word

### PR DESCRIPTION
**Pull request by a-r-1**

### CODE REVIEW

**Review by pnevares — CHANGES_REQUESTED** [review]
Thanks for opening the PR! The updates to Changelog 413 are probably unnecessary as they don't improve readability in my opinion, see more from Jerod here: https://github.com/thechangelog/transcripts/issues/23#issuecomment-538005735

However the change to 414 is fine, and I found a nearby unintelligible that was an easy fix and added it to the PR. If you can revert 413 I'll merge this!

**Comment by a-r-1** [comment]
Thanks @pnevares for the feedback - that's now done.

**Review by pnevares — APPROVED** [review]
🚢

**Comment by pnevares** [comment]
@all-contributors please add @a-r-1 for doc

**Pull request merged**
