### PR TITLE
Fix typos, add missing words, fix punctation in S01E02

### PR DESCRIPTION
**Pull request by TiSli**

### CODE REVIEW

**Comment by TiSli** [comment]
I PR'd my master again with both E01 and E02 changes because I forgot to branch. Third episode is on a different branch in PR #192

**Comment by jerodsanto** [comment]
@TiSli yeah you'll want to sync your master branch and then re-branch from that. I'm honestly not sure how (and if) you can do that from GitHub's web UI...

**Comment by Autofix** [comment]
@TiSli Just make sure you branch from master each time before committing otherwise the branch will include your previous commits. I've been submitting each branch as a separate pull request and then deleting the branch once it's merged.

**Comment by jerodsanto** [comment]
Yes, but your master branch needs to have our master branch merged (fast-forwarded, probably) into it before you branch off again, otherwise it's also behind. 

(I'm squash/merging these two PRs just to clear them out)

**Pull request merged**
