### PR TITLE
Update changelog--friends-41.md

### PR DESCRIPTION
**Pull request by ernstki**
- fix a few minor spelling mistakes and several of the [unintelligible]s
- link to definitions of some of the "business model 101" terms
- link to some of the IaC and related companies
- correct many mentions of album, band, song titles

### CODE REVIEW

**Comment by ernstki** [comment]
I _struggled_ to get through this one, @jerodsanto, did it anyway, for the team. If I never hear anyone say "the ol' hot and juicy" again in my life, it'll be soon enough.

**Comment by jerodsanto** [comment]
Amazing job, @ernstki! Thanks for taking one for the team 👏 

(but my general advice is to only listen to episodes that you're enjoying 😉)

**Comment by ernstki** [comment]
I was procrastinating something else, so.

Just for my edification, what're your thoughts on adding links to projects and companies mentioned _in_ the transcripts?

Life expectancy on any product or service in the infrastructure-as-code space is probably _already_ short, even before System Initiative eats all their lunches. It almost didn't seem worth it to linkify them.

Just stick to the high points and put URLs in the show notes from now on?

**Comment by jerodsanto** [comment]
I think most people will look for those links in the show notes vs the transcripts. Happy to have them in both places, but prioritizing show notes makes more sense to me.

**Pull request merged**
