### PR TITLE
Updated transcript for episode 464

### PR DESCRIPTION
**Pull request by w3bdev1**
Starting new year with it :)

### CODE REVIEW

**Comment by w3bdev1** [comment]
Added for episode 464

**Comment by jerodsanto** [comment]
Love it! If you intend to keep it going I’ll gladly add you as a collab on the repo so you don’t have to PR all the time 👌

**Comment by w3bdev1** [comment]
I'll be happy to be. So collab can merge PRs or what?

**Comment by jerodsanto** [comment]
Yup, you can merge PRs and you can also commit directly to the master branch which means you can improve transcripts without having to open a PR yourself ✊

**Pull request merged**
